---
id: readable-code-workshop-2019-09-24-conclusion
base_name: next-step
tags:
- rabbit
- readable-code
- sezemi
presentation_date: 2019-09-24
version: 2019.09.24
licenses:
- CC BY-SA 4.0
slideshare_id: readable-code-workshop-2019-09-24-conclusion
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: YUKI Hiroshi
  email: yuki@clear-code.com
  rubygems_user: Piro
  slideshare_user: pirooutsiderreflex
  speaker_deck_user: piroor
