---
id: readable-code-workshop-2015-03-06-code-change
base_name: how-to-look-back
tags:
- rabbit
- readable-code
presentation_date: 2015-03-06
version: 2015.3.6.1
licenses:
- CC BY-SA 4.0
slideshare_id: readable-code-workshop-2015-03-06-code-change
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
