---
id: readable-code-workshop-2019-09-24-implementation
base_name: how-to-proceed
tags:
- rabbit
- readable-code
presentation_date: 2019-09-24
version: 2019.09.24
licenses:
- CC BY-SA 4.0
slideshare_id: readable-code-workshop-2019-09-24-implementation
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: YUKI Hiroshi
  email: yuki@clear-code.com
  rubygems_user: piro_or
  slideshare_user: piro_or
  speaker_deck_user: piro_or
