---
id: readable-code-workshop-2022-08-05-retrospective
base_name: how-to-look-back
tags:
- rabbit
- readable-code
presentation_date: 2022-08-05
version: 2022.08.05
licenses:
- CC BY-SA 4.0
slideshare_id: readable-code-workshop-2022-08-05-retrospective
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: YUKI Hiroshi
  email: yuki@clear-code.com
  rubygems_user: Piro
  slideshare_user: pirooutsiderreflex
  speaker_deck_user: piroor
