---
id: readable-code-workshop-2022-08-04-performance
base_name: summary
tags:
- rabbit
- readable-code
presentation_date: 2022-08-04
version: 2022.08.04
licenses:
- CC BY-SA 4.0
slideshare_id: readable-code-workshop-2022-08-04-performance
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: YUKI Hiroshi
  email: yuki@clear-code.com
  rubygems_user: Piro
  slideshare_user: pirooutsiderreflex
  speaker_deck_user: piroor
