---
id: readable-code-workshop-2021-09-13-introduction
base_name: summary
tags:
- rabbit
- readable-code
presentation_date: 2021-09-13
version: 2021.09.13
licenses:
- CC-BY-SA-4.0
slideshare_id: readable-code-workshop-2021-09-13-introduction
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: YUKI Hiroshi
  email: yuki@clear-code.com
  rubygems_user: Piro
  slideshare_user: pirooutsiderreflex
  speaker_deck_user: piroor
