---
id: readable-code-workshop-for-pioneer-introduction
base_name: summary
tags:
- rabbit
- readable-code
presentation_date: 2015-08-11
version: 2015.8.11.0
licenses:
- CC BY-SA 4.0
slideshare_id: readable-code-workshop-for-pioneer-introduction
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
